#+TITLE: Subhashis's Hyprland Config
#+AUTHOR: Subhashis Barad
#+PROPERTY: header-args :tangle hyprland.conf
#+auto_tangle: t
#+STARTUP: showeverything
This file can be tangled into hyprland.conf. Read and understand the config and tinker it as to your will 😊
* Table Of Contents :toc:
- [[#monitor][Monitor]]
- [[#variables][Variables]]
  - [[#keywords][Keywords]]
  - [[#environment-variables][Environment Variables]]
  - [[#input][Input]]
  - [[#misc][Misc]]
  - [[#general][General]]
  - [[#decoration][Decoration]]
- [[#startup][Startup]]
- [[#animations][Animations]]
- [[#window-layouts][Window Layouts]]
- [[#window-rules][Window Rules]]
- [[#gestures--misc][gestures & misc]]
- [[#keybindings][Keybindings]]
  - [[#app-launchers][App Launchers]]
  - [[#windows-navigation][Windows Navigation]]
  - [[#system][System]]
  - [[#wireplumberpipewire][Wireplumber(Pipewire)]]
  - [[#pulseaudio][PulseAudio]]
  - [[#playerctl][Playerctl]]

* Monitor
Defining monitor details and specifying it to Hyprland is done through this code block. [[https://wiki.hyprland.org/Configuring/Monitors/][click here to read more]]
#+BEGIN_SRC conf
monitor=,preferred,auto,auto
#+END_SRC

* Variables
Variables can be used to configure the behavior of the program, define constants, or store information that the program will reference later. [[https://wiki.hyprland.org/Configuring/Variables/][read more]]

** Keywords
These definitions/keywords are used by a user to define the commonly used terms throughout the codespace, it generally starts by a '$' and you can name it anything & use it instead of adding the whole command/line everywhere, in order to give a clean and professional look to your code. [[https://wiki.hyprland.org/Configuring/Keywords/][read more]]

#+BEGIN_SRC conf
$mainMod = SUPER
$SCRIPTS = $HOME/.config/hypr/scripts
$myBrowser = brave
$myTerm = kitty
$myFM = nemo
$myEditor = emacsclient -c -a 'emacs'
$myRL = rofi -show drun
##$myBar = env GTK_THEME=Minwaita-Vanilla-Dark waybar
$myBar = gBar bar 0
$CONFIG = $HOME/.config/ 
#+END_SRC

** Environment Variables
An environment variable, essentially a named container with data, is utilized by multiple applications for configuration settings. While Linux newcomers may initially find it complex, these variables simplify the sharing of settings across applications and processes. [[https://wiki.hyprland.org/Configuring/Environment-variables/][read more]]

#+BEGIN_SRC conf
env = XCURSOR_SIZE,24
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots
env = QT_QPA_PLATFORMTHEME, qt5ct
env = QT_QPA_PLATFORMTHEME, qt6ct
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
env = GDK_BACKEND, wayland,x11
env = QT_QPA_PLATFORM, wayland;xcb
env = XCURSOR_THEME, Bibata-Modern-Ice
env = GTK_THEME, Catppuccin-Macchiato-Standard-Sapphire-Dark
#+END_SRC

** Input
#+BEGIN_SRC conf

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}


#+END_SRC

** Misc

#+BEGIN_SRC conf
misc {
     disable_hyprland_logo = true
     disable_splash_rendering = true

}
#+END_SRC

** General

#+BEGIN_SRC conf
general {
    gaps_in = 3
    gaps_out = 7
    border_size = 2
    col.active_border = rgba(00FFFFCC) rgba(FF69B4CC) 45deg
    col.inactive_border = rgba(C0C0C080)
    layout = master
}
#+END_SRC

** Decoration

#+BEGIN_SRC conf
decoration {
    rounding = 5

        blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }

    active_opacity = 1.0
    inactive_opacity = 0.70
    fullscreen_opacity = 1.0
    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}
#+END_SRC

* Startup
This section defines all that apps/programmes we want to get executed at launch of hyprland.

#+BEGIN_SRC conf
exec-once = $myBar 
exec-once = variety
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/bin/emacs --daemon
exec-once = systemctl import-environment --user WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland 
exec-once = $SCRIPTS/startup
exec-once = $SCRIPTS/settheme
exec-once = hyprctl setcursor Bibata-Modern-Ice 24 
#+END_SRC


* Animations
This code block defines and directs Hyprland how it must present the animation in accordance with our specifications. [[https://wiki.hyprland.org/Configuring/Animations/][read more]]

#+BEGIN_SRC conf
animations {
    enabled = yes

      bezier = myBezier, 0.05, 0.9, 0.1, 1.05
      bezier = wind, 0.05, 0.9, 0.1, 1.05
      bezier = winIn, 0.1, 1.1, 0.4, 1.05
      bezier = winOut, 0.3, -0.3, 0, 1
      bezier = liner, 1, 1, 1, 1

  animation = windows, 1, 4, wind, slide
  animation = windowsIn, 1, 4, winIn, slide
  animation = windowsOut, 1, 4, winOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, loop
  animation = fade, 1, 10, default
  animation = workspaces, 1, 3, wind
}
#+END_SRC

* Window Layouts
In Window Layouts section, we specify Hyprland to use a specific kind of layout between [[https://wiki.hyprland.org/Configuring/Dwindle-Layout/][dwindle]] and [[https://wiki.hyprland.org/Configuring/Master-Layout/][master]]. I personally like the master layout. Since I have been using Xmonad since very long and in it, master is by default.
#+BEGIN_SRC conf
dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    new_is_master = true
    mfact = 0.5
}
#+END_SRC
* Window Rules
#+begin_src conf
#Calcurse
windowrulev2 = move 1429 526, class:^(kitty)$, title:^(cava)$
windowrulev2 = size 25% 50%, class:^(kitty)$, title:^(cava)$
windowrulev2 = float, class:^(kitty)$, title:^(cava)$

windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$

#+end_src
* gestures & misc

#+BEGIN_SRC conf
gestures {
    workspace_swipe = off
}

device:epic-mouse-v1 {
    sensitivity = -0.5
}
#+END_SRC

* Keybindings
All the keybindings are specified in this section.
** App Launchers

#+BEGIN_SRC conf
bind = $mainMod, return, exec, $myTerm
bind = $mainMod SHIFT, F, exec, $myFM
bind = $mainMod, P, exec, $myRL
bind = $mainMod, B, exec, $myBrowser
bind = $mainMod, space, fullscreen
bind = $mainMod, E, exec, $myEditor
bind = $mainMod, H, exec, hyprctl dispatch splitratio -0.1
bind = $mainMod, L, exec, hyprctl dispatch splitratio 0.1
bind = CTRL SHIFT, Escape,exec, kitty -e bpytop
bind =, PRINT, exec ,hyprshot -m region
bind = $mainMod SHIFT, N, exec, variety -n
bind = $mainMod SHIFT, R, exec, killall gBar && hyprctl dispatch exec $myBar
bind = $mainMod SHIFT, E, exec, rofi -show emoji
bind = $mainMod CTRL, C, exec, kitty -e cava
#+END_SRC 

** Windows Navigation

#+BEGIN_SRC conf
bind = $mainMod SHIFT, right, swapnext
bind = $mainMod SHIFT, left, swapnext
bind = $mainMod, Q, killactive, 
bind = $mainMod, V, togglefloating, 
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#+END_SRC
** System

#+begin_src conf
bind = $mainMod CTRL, N, exec, hyprctl keyword decoration:screen_shader $SCRIPTS/shaders && notify-send "Night Light is Enabled"
bind = $mainMod CTRL , R , exec, hyprctl reload && notify-send "Night Light is Disabled"
bind = $mainMod SHIFT, N, exec, variety -n
bind = $mainMod SHIFT, P, exec, variety -p
bind = $mainMod, W, exec, $CONFIG/rofi/scripts/rofi-wifi-menu
bind = $mainMod, X, exec, $CONFIG/rofi/scripts/powermenu
#+end_src

** Wireplumber(Pipewire)
#+BEGIN_SRC conf
###Pipewire
# bind=,XF86AudioMute,exec,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bind=,XF86AudioRaiseVolume,exec,wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
# bind=,XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
#+END_SRC

** PulseAudio

#+BEGIN_SRC conf
###PulseAudio
bind=,XF86AudioMute,exec, pamixer -t
bind=,XF86AudioRaiseVolume,exec, pamixer -i 5 
bind=,XF86AudioLowerVolume,exec, pamixer -d 5 
#+END_SRC
** Playerctl

#+begin_src conf
bind = $mainMod CTRL, left, exec, playerctl next
bind = $mainMod CTRL, right, exec, playerctl next
bind = $mainMod CTRL, space, exec, playerctl play-pause
#+end_src
